### ISSUE TITLE
Whether the update time of the package can be displayed

### ISSUE THREAD

**Issue by Yakumo-Yukari** [nimpkgs/website#3]
![111](https://github.com/user-attachments/assets/f37abb7d-f50f-4d66-8495-74d7c798e363)

When searching for packages that haven't been updated in years, is it possible to display their last update time in the results list?

**Comment by daylinmorgan** [comment]
Added in f8b3c95

I've gone with the commit date over the last version release since the community can be bad about tagging releases.
